### ISSUE TITLE
Package breaks calendar autoloads

### ISSUE THREAD

**Issue by ghost** [misohena/moonrise-el#1]
Hi,

I have added your package's directory to load-path and compiled the elisp file moonrise.el.  After restarting Emacs, M-x calendar was broken - obviously all autoloaded calendar related functions were not known anymore to Emacs.

After deleting the cal-loaddefs.el file that was generated when compiling moonrise.el the problem disappeared.  I guess this second cal-loaddefs.el shadows the original calendar loaddefs file, which is a problem.  Or something like that.

I guess ;;;###cal-autoload works differently than normal autoload and one should not use it.  But I dunno.  Same problem for diary autoloads I guess.

Could you please investigate?

Apart from that package looks very nice!

Second question: do you plan to add your packages to Gnu Elpa some day?

TIA, Michael.

**Comment by misohena** [comment]
(Google Translate)
Hello michael-heerdegen.

Thank you for letting me know about the autoload issue.

I tried modifying the autoload comment in commit 656d6b3b6664d198da70b4346a32e6261ac1e9f0, but will this solve the problem?

I don't plan on registering any Emacs packages I create with package archives. There are several reasons for this, including the language barrier of English and not wanting to be burdened with more than just creating what I want. This software is distributed under a free license. Users have the right to freely improve and redistribute it, so anyone who wants to register can do so without my permission.

I hope it translates well.

(Orignal Message)
michael-heerdegenさんこんにちは。

autoloadの問題について教えて頂きありがとうございます。

コミット 656d6b3b6664d198da70b4346a32e6261ac1e9f0 にてautoloadコメントを修正してみましたが、これで解決するでしょうか。

パッケージアーカイブへの登録については、私が作るどのEmacs用パッケージにおいても計画していません。英語という言語の壁があること、自分が欲しいものを作るという以上の負担を負いたくないこと等理由はいくつかあります。このソフトウェアは自由なライセンスの元配布しています。利用者は自由に改良し再配布する権利がありますので、登録したい方が私の許可無くそれを行うことが出来ます。

うまく翻訳されると良いのですが。

**Comment by ghost** [comment]
AKIYAMA Kouhei ***@***.***> writes:

> I tried modifying the autoload comment in commit 656d6b3, but will
> this solve the problem?

Yes, it does.  Thank you very much.

> I don't plan on registering any Emacs packages I create with package
> archives. There are several reasons for this, including the language
> barrier of English and not wanting to be burdened with more than just
> creating what I want.

Would you accept my help?

There is actually not much work involved to add something to Gnu Elpa.
I have access to the Gnu Elpa repo so I would be able to do the uploads.

Your packages are usable out of the box, don't worry about
documentation.

Edraw had been presented and discussed in the Emacs Berlin meetup (so we
even have a video already for that one!), and we wondered if it would
appear in Gnu Elpa.

Or are there political reasons for why you don't want to give copyright
to the FSF?

The problem for emacs-dev is that if you don't grant the copyright to
the FSF, emacs-dev is not allowed to reuse your code.  This is necessary
for lawyer reasons ... dunno, to prevent that your employer, for
example, can sue the FSF telling that it's actually their code and
demand a huge sum of money, such things as far as I understand.  That's
why you have to sign a sheet of paper telling that you didn't write the
code for your company.

Advantage for you is that your code is better discoverable and easier to
use for the Emacs community.

I don't think that there are many disadvantages.  In few cases it
happened that the version of a package in Gnu Elpa and the one of the
original author diverged.  This doesn't happen happen often, though, and
there are ways to deal with it.  Doing nothing in this case even is
ok, you can still develop your version as you want and let emacs-dev
merge changes from your version.

**Comment by misohena** [comment]
(Translated Message)
I'm glad you solved it.

Regarding registration in the package archive, I wrote the following in the el-easydraw README.

> This software is licensed under GPLv3. You are free to use, modify and distribute this software.
> If you wish to register this software in any package archive, please fork this repository, make the necessary modifications to fit the package archive’s requirements, and submit the registration on your own. Also continue with the necessary maintenance. You don’t need my permission.

What is the problem?

> Advantage for you is that your code is better discoverable and easier to use for the Emacs community.

I feel like there is some misunderstanding here. That's not an advantage for me, but for anyone who wants to obtain software via ELPA.

So many people try to put the burden on me by saying things like that. I believe he meant no harm, but I don't think it's fair. The burden should be borne by those who enjoy the benefits.

Some developers seem to want the software they create to be used by as many people as possible, but I don't agree with that. Having a large number of people using it is not only good for developers. If English issues come more frequently, I might not be able to deal with them.

I write software driven by the passion I want to create (that passion is very delicate and easily destroyed in interactions with others),
And I just made the product public for a little kindness and fame. That's all I can do.

> I don't think that there are many disadvantages.
> In few cases it happened that the version of a package in Gnu Elpa and the one of the original author diverged.

I don't think it matters much. Having multiple versions is proof that freedom is working.

> This doesn't happen happen often, though, and there are ways to deal with it.
> Doing nothing in this case even is ok, you can still develop your version as you want and let emacs-dev merge changes from your version.

This is a problem. I don't want to go through the trouble of communicating with others when releasing software I've written. That too in English!

Communicating in English is probably many times more painful for me than you can imagine. I have no intention of assuming any obligation to do such things on a regular basis.

> Or are there political reasons for why you don't want to give copyright to the FSF?
> The problem for emacs-dev is that if you don't grant the copyright to the FSF, emacs-dev is not allowed to reuse your code.  This is necessary for lawyer reasons ... dunno, to prevent that your employer, for example, can sue the FSF telling that it's actually their code and demand a huge sum of money, such things as far as I understand.  That's why you have to sign a sheet of paper telling that you didn't write the code for your company.

I don't know much about ELPA's policies. I've only heard a few bits and pieces. I don't have the ability to follow the vast amount of discussion in English.

I have no interest in protecting my copyright when it comes to Emacs-related software. I don't belong to a company, so this shouldn't be a problem.

In the first place, I always feel that package systems are overrated in the world. Is it really that difficult to just put el somewhere along the load-path (although it is certainly useful when there are complex dependencies)? I haven't installed my self-made Elisp via the package system. I am making it a submodule of the Emacs configuration directory managed by Git. Therefore, registering to the package archive is not completely "for me".

The package system is certainly convenient for users. But it's not always good for developers. I heard that in a certain famous package archive, people are forced to modify even the way comments are written (I don't know about ELPA, though). It seems that this is to maintain the quality of the software for the users, but to put it bluntly, this is going too far. If I asked the FSF to fix GNU's C coding style, the abnormality would be obvious. I will never give up the right to write code in my own free coding style.

Therefore, I have no intention of registering it to the package archive myself. On the other hand, I do not intend to prevent anyone from registering. I can cooperate as long as it is within the scope that I can tolerate. In any case, people who truly want to register should do it voluntarily.

> Edraw had been presented and discussed in the Emacs Berlin meetup (so we even have a video already for that one!), and we wondered if it would appear in Gnu Elpa.

Thank you for letting me know. It makes me happy to see what I create being appreciated.

When I back-translate this comment (from English to Japanese), there are some parts where the meaning has changed, but that's all I can correct. This is the result of several hours of struggling with translation software. tired.

(Original Message)
解決して良かったです。

パッケージアーカイブへの登録についてですが、私はel-easydrawのREADMEに次のように書きました。

> This software is licensed under GPLv3. You are free to use, modify and distribute this software.
> If you wish to register this software in any package archive, please fork this repository, make the necessary modifications to fit the package archive’s requirements, and submit the registration on your own. Also continue with the necessary maintenance. You don’t need my permission.

問題は何でしょうか。

> Advantage for you is that your code is better discoverable and easier to use for the Emacs community.
> あなたにとっての利点は、コードが Emacs コミュニティでより見つけやすくなり、使いやすくなることです。

ここに何か誤解があるような気がします。それは私にとっての利点ではなく、ELPA経由でソフトウェアを入手したい人の利点です。

非常に多くの人がそのようなことを言って私に負担を押し付けようとしてきます。悪気はないのだと信じますが、それは公平ではないと思います。利点を享受する人が負担を負うべきです。

一部の開発者は自分が作ったソフトウェアを可能な限り多くの人に使ってほしいと思うようですが、私はそうではありません。沢山の人が利用することは開発者にとって良いことばかりではありません。もし英語のIssueがこれ以上頻繁に来ると私は対処できなくなる可能性があります。

私は自分が作りたいという情熱に駆動されてソフトウェアを書き(そういった情熱はとても繊細で他人との関わりの中で簡単に壊れてしまうものです)、そしてその産物をちょっとした親切心と功名心のようなもののために公開しただけです。私に出来るのはそこまでです。

> I don't think that there are many disadvantages.
> In few cases it happened that the version of a package in Gnu Elpa and the one of the original author diverged.
> デメリットはあまりないと思います。 まれに、Gnu Elpa のパッケージのバージョンとオリジナルの作成者のバージョンが異なることが起こりました。

私はそれはあまり問題では無いと思います。複数のバージョンがあることは自由さが健全に機能している証拠です。

> This doesn't happen happen often, though, and there are ways to deal with it.
> Doing nothing in this case even is ok, you can still develop your version as you want and let emacs-dev merge changes from your version.
> ただし、これは頻繁に起こることではなく、それに対処する方法があります。
> この場合は何もしなくても大丈夫です。必要に応じてバージョンを開発し、emacs-dev にバージョンからの変更をマージさせることができます。

これは問題です。私は私が書いたソフトウェアのリリースに際して、他人とコミュニケーションを取る手間をかけたいとは思いません。それも英語で！

私が英語でコミュニケーションを取ることはおそらくあなたが想像しているよりも何倍も私にとっては苦痛です。そのようなことを定期的に行うような義務を私は一切負うつもりはないのです。

> Or are there political reasons for why you don't want to give copyright to the FSF?
> それともFSFに著作権を与えたくない政治的な理由があるのでしょうか？
> The problem for emacs-dev is that if you don't grant the copyright to the FSF, emacs-dev is not allowed to reuse your code.  This is necessary for lawyer reasons ... dunno, to prevent that your employer, for example, can sue the FSF telling that it's actually their code and demand a huge sum of money, such things as far as I understand.  That's why you have to sign a sheet of paper telling that you didn't write the code for your company.
> emacs-dev の問題は、FSF に著作権を付与しないと、emacs-dev がコードを再利用できないことです。 これは弁護士の理由で必要です...わかりませんが、たとえばあなたの雇用主がFSFを訴えて、それが実際には自分たちの暗号であると言って巨額の金銭を要求することを防ぐためです、私の理解する限りでは、そのようなことです。 そのため、自分の会社のためにコードを書いたものではないことを示す紙に署名する必要があります。

ELPAのポリシーについて私は多くは知りません。断片的にいくつか聞いたことがある程度です。膨大な量の英語での議論を追う能力は私にはありません。

私はことEmacs関連のソフトウェアに関しては、自分の著作権を守ることは興味はありません。会社にも所属していないので、そういったことが問題になることは無いでしょう。


そもそも私は世の中でパッケージシステムが過大評価されていると常々感じています。load-pathの通る所にelを置くだけのことがそれほど大変でしょうか(複雑な依存関係がある場合は確かに便利ではあります)。私は自分で作ったElispをパッケージシステムを経由してインストールしていません。Gitで管理しているEmacs構成ディレクトリのサブモジュールにしています。なのでパッケージアーカイブへ登録することは完全に「私のため」ではありません。

パッケージシステムは利用者にとっては確かに便利です。しかし開発者にとっては必ずしも良いものとは限りません。とある有名なパッケージアーカイプではコメントの書き方一つについても修正を迫ってくると聞きました(ELPAがどうかは知りませんが)。ユーザーのためにソフトウェアの品質を保つためだそうですが、ハッキリ言って行きすぎです。もし私がFSFにGNUのC言語のコーディングスタイルを直せと要求したらその異常性は明らかでしょう。私は自分が自由なコーディングスタイルでコードを書く権利を絶対に手放したりしません。

というわけで、私は自分からパッケージアーカイブへ登録するつもりはありません。一方で誰かが登録することを妨げるつもりもありません。私が許容できる範囲内であれば協力することも出来ます。いずれにせよ、登録を真に望む情熱のある人が自主的に行えば良いのです。

> Edraw had been presented and discussed in the Emacs Berlin meetup (so we even have a video already for that one!), and we wondered if it would appear in Gnu Elpa.
> Edraw は Emacs ベルリンのミートアップで紹介され、議論されていました (つまり、そのビデオもすでに用意されています!) ので、私たちはそれが Gnu Elpa に登場するのではないかと疑問に思いました。

教えて頂きありがとうございます。作ったものが評価されるのを見るのは嬉しいものです。

このコメント逆翻訳(英語→日本語)すると意味が変わっている箇所があるのですが、私に修正出来るのはここまでです。数時間翻訳ソフトと格闘した結果です。疲れた。

**Comment by ghost** [comment]
Hello Kouhei,

> This is the result of several hours of struggling with translation
> software. tired.

Oh fuck - I'm extremely sorry.  I'll try to make it very short.  I more
or less feel exactly the same as you, I'm also a contributor and hate
all of this kind of things.  Also the need to speak English, but to a lesser
degree than you.

>  If you wish to register this software in any package archive, please fork this
>  repository, make the necessary modifications to fit the package archive’s
>  requirements, and submit the registration on your own. Also continue with the
>  necessary maintenance. You don’t need my permission.

Thanks!  Only problem: for Gnu Elpa FSF does need your explicit
permission, for legal reasons I had explained.  Would you accept to
provide it?  You would receive them per email.  I would arrange for
that.

> This is a problem. I don't want to go through the trouble of
> communicating with others when releasing software I've written. That
> too in English!

There is no need to do that, actually, if you prefer to work alone.

> I heard that in a certain famous package archive, people are forced to
> modify even the way comments are written (I don't know about ELPA,
> though).

Hmm - I think it's that strict only in the Emacs repo. 


Ok, I volunteer to get in contact with emacs-dev and will completely
avoid to contact you.  The only question is whether I'm allowed to aim
to add your packages to Gnu Elpa - which would mean you would have to
put your signature under a piece of paper - or else I think we can still
add it to the nongnu archive.

Thanks for your patience and effort.

**Comment by misohena** [comment]
(Translated Message)
> Thanks!  Only problem: for Gnu Elpa FSF does need your explicit permission, for legal reasons I had explained.  Would you accept to provide it?  You would receive them per email.  I would arrange for that.

This depends on the terms of the contract. But there is a possibility. As I've said before, I want to maintain a coding environment that is as free and free of unnecessary communication burdens as possible, and I'm always concerned that contracts will undermine that. However, it's a matter of concern as I continue development, so it doesn't matter if I don't continue development. In other words, one option is for me to step back from development and entrust the future to a third party who can accept that burden.

> Hmm - I think it's that strict only in the Emacs repo.

I previously received a pull request from someone who wanted to register with MELPA for another project, and there were corrections to comments, parentheses, etc. When I asked why, he said it had to pass lint. I don't know the details. When I refused, he announced that he had forked the repository and taken over the project. The interaction with him was a little unpleasant, but I think he should do it if he wants to.

Anyway, good luck!

(Original Message)
> Thanks!  Only problem: for Gnu Elpa FSF does need your explicit permission, for legal reasons I had explained.  Would you accept to provide it?  You would receive them per email.  I would arrange for that.

これは契約の内容次第です。しかし可能性はあるでしょう。従前も述べたように私は出来る限り自由で余計なコミュニケーション負担の少ないコーディング環境を維持したいと考えており、契約によってそれが損なわれることは常に懸念事項です。ただし、それは私が開発を続けるときに問題になる事項なので、私が開発を続けなければ問題になりません。つまり、私が開発から手を引きそういった負担を受け入れられる第三者に今後を託すのも選択肢の一つです。

> Hmm - I think it's that strict only in the Emacs repo.

以前別のプロジェクトでMELPAに登録したい人からのpull requestがあり、その中にコメントやカッコの位置などの修正がありました。理由を尋ねたらlintにパスしなければならないのだとか。詳しくは知りません。私が拒否すると彼はリポジトリをフォークしてプロジェクトを引き取ったとアナウンスしていました。彼とのやりとりは少々不愉快さを伴いましたが、彼がそうしたいならそうすれば良いと私は思います。

何はともあれ、幸運を祈ります！

**Comment by ghost** [comment]
Hello Kouhei,

> This depends on the terms of the contract.

Let me ask on emacs-dev what they think we could do.  Ok?

> I previously received a pull request from someone who wanted to
> register with MELPA for another project, and there were corrections to
> comments, parentheses, etc. [...]

MELPA is a third-party project.

For Gnu Elpa emacs-dev doesn't care that much about stylistic stuff.
The only relevant thing is that the package header holds some necessary
fields (package version, required minimum Emacs version).  But this is a
trivial thing.  And your code comments should not tell people to kill
someone and such obvious things.

Michael.

**Comment by misohena** [comment]
(Translated Message)
Anything I write and publish for Emacs is a gift to everyone who uses Emacs, so please do with it as you like.
Regarding copyright handling, I am simply stating the obvious that I cannot decide whether to sign or not until I see something concrete.
If there is an obligation imposed on me, it must be something that I can commit to 100%. It is common to find clauses in unexpected places that say otherwise.
If it's what you say, I think there's probably no problem.

(Original Message)
私がEmacsのために書いて公開したものはEmacsを使っている全て皆さんへのプレゼントですから、好きなようにしてください。
著作権の処理については、私は具体的なものを見なければサインするか決められないという当たり前のことを言っているだけです。
もし私に課せられる義務があるならば、それは私が100%お約束できるものでなければなりません。意外なところにそうではないような条文が入っているということは良くあることです。
あなたが言うとおりならおそらく問題ないと思いますよ。

**Comment by ghost** [comment]
AKIYAMA Kouhei ***@***.***> writes:

> [...] If it's what you say, I think there's probably no problem.

Yes, that's what I meant.

Ok, I've explained the situation to emacs-dev and you will be contacted
using the email address mentioned in your blog, if everything goes well.

Thanks again for you patience.

**Comment by misohena** [comment]
(Translated Message)
Hello Michael.

It took quite some time (I sent the signed PDF on the 7th), but I received notification that the FSF's copyright assignment process for GNU EMACS has been completed.

There was a question asking for the modified file, and since you mentioned Edraw above, I answered https://github.com/misohena/el-easydraw (this is moonrise-el's issue However). Please let us know if there are any other processes required.

(Original Message)
Michaelさんこんにちは。

かなり時間がかかりましたが(署名したPDFを7日に送りました)、GNU EMACSに関するFSFによる著作権割り当てプロセスが完了したとの連絡を受け取りました。

修正したファイルを問われる質問がありましたが、上であなたがEdrawに言及されていたので https://github.com/misohena/el-easydraw と答えておきました(ここは moonrise-el のIssueではありますが)。他に必要なプロセスがあればお知らせ下さい。

**Comment by ghost** [comment]
AKIYAMA Kouhei ***@***.***> writes:

> It took quite some time (I sent the signed PDF on the 7th), but I
> received notification that the FSF's copyright assignment process for
> GNU EMACS has been completed.

Very good.  Thank you so much!

> There was a question asking for the modified file, and since you mentioned Edraw
> above, I answered https://github.com/misohena/el-easydraw (this is moonrise-el's
> issue However). Please let us know if there are any other processes required.

I'll just talk to Daniel per Email, ok? (I currently can't log into
Github).

I'll keep you CC'd just for politeness but you can simply ignore
everything, since I promised not to bother you from now on.


Thanks,

Michael.
